[package]
name = "sulfctl"
version = "0.1.0"
authors = ["Matteowoomy"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.20"
console = "0.13.0"
users = "0.11"